name: Justin M. LaPre
description: Potentially helpful tips and tricks I've learned or made up.
markdown: redcarpet
highlighter: rouge

kramdown:
  input: GFM

redcarpet:
    extensions: ["with_toc_data", "no_intra_emphasis", "tables"]

# gems:
#   - jekyll-knitr
#   - 'jekyll-pandoc-multiple-formats'
# gems: ['jekyll/scholar']

keep_files:  ['fig']

knitr:
  # opts_knit:
  #   base.dir: '_site/fig/'
  opts_chunk:
    fig.width: 5
    fig.height: 4
    fig.path: 'fig/'
    echo: FALSE
    message: FALSE
    warning: FALSE
    error: FALSE
    dev: svg

# pandoc:
#   skip: true
#   impose: false
#   output: ./tmp
#   flags: '--smart --bibliography=_data/refs.bib --csl=_data/ieee.csl'
#   # site_flags: '--toc'
#   outputs:
#     pdf: '--latex-engine=latex'
#   #   epub:
#   #   markdown:

madoko:
  Bibliography: /common.bib
  Bib style: plainnat
  Bib Search Url: google.com
  Heading Depth: 0      # suppress numbering sections
  meta: |
    ~Fig: label='Figure [@fig]{.figure-label}' .align-center
          after='&nl;&nl;\
                 [[**&label;.** ]\
                 {.caption-before}&caption;]\
                 {.figure-caption html-elem=fig-caption}\
                 &nl;{notag}&nl;'
          toc=tof toc-line='&label;. &caption;'
          html-elem=figure
          html-elem=figure

scholar:
  style: ieee
  locale: en

  sort_by: none
  order: ascending

  source: ./_data
  bibliography: refs.bib
  bibliography_template: |
    {{reference}}

  replace_strings: true
  join_strings:    true

  # details_dir:    bibliography
  # details_layout: bibtex.html
  # details_link:   Details
  # query: "@*"

base: ''

front_page_news: 6

url: http://www.cs.rpi.edu/~laprej/

permalink: /posts/:title.html

exclude:
  - README.md
  - Makefile
  - .madoko
  - common.bib
  - common.R

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: Courses
      link: /courses/
    - title: CV
      link: /cv.html
    - title: Calendar
      link: /calendar.html
    - title: Posts
      link: /posts/
    - title:
      link: http://github.com/laprej
      icon: /img/GitHub-Mark.png
      icon2x: /img/GitHub-Mark@2x.png
    - title:
      link: http://twitter.com/laprej
      icon: /img/twitter-logo.png
      icon2x: /img/twitter-logo@2x.png
